In [10]:
import pandas as pd
import numpy as np

#### Goal: Dividing the lung FPKM according to ecah phenotype to a seperate csv file for model reconstruction

In [11]:
## Data Source: https://filetransfer.mdc-berlin.de/

In [12]:
df1 = pd.read_csv('data/time_series_study/SupplementaryData2_Calu3_polyA_series1_fpkm.tsv',sep='\t')
df2 = pd.read_csv('data/time_series_study/SupplementaryData3_Calu3_polyA_series2_fpkm.tsv',sep='\t')
df3 = pd.read_csv('data/time_series_study/SupplementaryData5_H1299_polyA_fpkm.tsv',sep='\t')

In [13]:
dfs = [df1, df2, df3]
dfs = [df.set_index('gene_id||gene_name').drop(columns=['length']) for df in dfs]
df = dfs[0].join(dfs[1:])

In [14]:
df['genes'] = df.index
df.index = df['genes'].apply(lambda x:x.split('||')[1])
df = df.drop(columns=['genes'])

In [15]:
df.shape

(45057, 60)

In [16]:
df.head()

,Calu3_polyA_series1-S1-4h-A,Calu3_polyA_series1-S1-4h-B,Calu3_polyA_series1-S1-12h-A,Calu3_polyA_series1-S1-12h-B,Calu3_polyA_series1-S1-24h-A,Calu3_polyA_series1-S1-24h-A-detachedcells,Calu3_polyA_series1-S1-24h-B,Calu3_polyA_series1-S1-24h-B-detachedcells,Calu3_polyA_series1-S2-4h-A,Calu3_polyA_series1-S2-4h-B,...,H1299_polyA_S2-24h-A,H1299_polyA_S2-24h-B,H1299_polyA_S2-36h-A,H1299_polyA_S2-36h-B,H1299_polyA_mock-4h-A,H1299_polyA_mock-4h-B,H1299_polyA_mock-36h-A,H1299_polyA_mock-36h-B,H1299_polyA_untr-4h-A,H1299_polyA_untr-4h-B
genes,,,,,,,,,,,,,,,,,,,,,
ETV5-AS1,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
LINC01299,0.000,0.000,0.000,0.000,0.000,0.154,0.000,0.000,0.000,0.029,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
MLLT3,5.190,5.600,6.417,6.497,7.833,7.608,6.875,9.475,4.435,4.974,...,4.287,4.033,3.814,3.549,3.750,3.820,3.970,4.311,4.081,3.734
SCGB3A2,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
SEPT10P1,0.856,1.022,1.110,0.419,1.400,1.047,1.172,1.977,1.259,0.733,...,2.090,1.429,1.462,1.729,1.867,1.586,2.387,2.268,2.350,1.254

In [17]:
df.columns

Index(['Calu3_polyA_series1-S1-4h-A', 'Calu3_polyA_series1-S1-4h-B',
       'Calu3_polyA_series1-S1-12h-A', 'Calu3_polyA_series1-S1-12h-B',
       'Calu3_polyA_series1-S1-24h-A',
       'Calu3_polyA_series1-S1-24h-A-detachedcells',
       'Calu3_polyA_series1-S1-24h-B',
       'Calu3_polyA_series1-S1-24h-B-detachedcells',
       'Calu3_polyA_series1-S2-4h-A', 'Calu3_polyA_series1-S2-4h-B',
       'Calu3_polyA_series1-S2-12h-A', 'Calu3_polyA_series1-S2-12h-B',
       'Calu3_polyA_series1-S2-24h-A',
       'Calu3_polyA_series1-S2-24h-A-detachedcells',
       'Calu3_polyA_series1-S2-24h-B',
       'Calu3_polyA_series1-S2-24h-B-detachedcells',
       'Calu3_polyA_series1-mock-4h-A', 'Calu3_polyA_series1-mock-4h-B',
       'Calu3_polyA_series1-mock-24h-A', 'Calu3_polyA_series1-mock-24h-B',
       'Calu3_polyA_series1-untr-4h-A', 'Calu3_polyA_series1-untr-4h-B',
       'Calu3_polyA_series2-4h-S1-1', 'Calu3_polyA_series2-4h-S1-2',
       'Calu3_polyA_series2-4h-S2-1', 'Calu3_polyA_series2-4h-S2-2',
       'Calu3_polyA_series2-4h-mock-1', 'Calu3_polyA_series2-4h-mock-2',
       'Calu3_polyA_series2-8h-S1-1', 'Calu3_polyA_series2-8h-S1-2',
       'Calu3_polyA_series2-8h-S2-1', 'Calu3_polyA_series2-8h-S2-2',
       'Calu3_polyA_series2-12h-S1-1', 'Calu3_polyA_series2-12h-S1-2',
       'Calu3_polyA_series2-12h-S2-1', 'Calu3_polyA_series2-12h-S2-2',
       'Calu3_polyA_series2-12h-mock-1', 'Calu3_polyA_series2-12h-mock-2',
       'H1299_polyA_S1-4h-A', 'H1299_polyA_S1-4h-B', 'H1299_polyA_S1-12h-A',
       'H1299_polyA_S1-12h-B', 'H1299_polyA_S1-24h-A', 'H1299_polyA_S1-24h-B',
       'H1299_polyA_S1-36h-A', 'H1299_polyA_S1-36h-B', 'H1299_polyA_S2-4h-A',
       'H1299_polyA_S2-4h-B', 'H1299_polyA_S2-12h-A', 'H1299_polyA_S2-12h-B',
       'H1299_polyA_S2-24h-A', 'H1299_polyA_S2-24h-B', 'H1299_polyA_S2-36h-A',
       'H1299_polyA_S2-36h-B', 'H1299_polyA_mock-4h-A',
       'H1299_polyA_mock-4h-B', 'H1299_polyA_mock-36h-A',
       'H1299_polyA_mock-36h-B', 'H1299_polyA_untr-4h-A',
       'H1299_polyA_untr-4h-B'],
      dtype='object')

In [18]:
x = 'H1299_polyA_untr-44h-B'
x[x.find('h-')-3 :x.find('h-')].split('-')[1]

'44'

In [19]:
meta = pd.DataFrame()
meta['filename'] = df.columns
#remove SARS1 smaples
meta = meta.loc[~meta.filename.str.contains('S1'),:]
meta = meta.loc[~meta.filename.str.contains('untr'),:]
meta = meta.loc[~meta.filename.str.contains('detached'),:]

meta['Cell_Line'] = meta['filename'].apply(lambda x:x.split('_')[0])
#meta['phenotype'] = meta['filename'].apply(lambda x :'_'.join(x.split('_')[-1].split('-')[:-1]))

meta['Time_Point'] = meta['filename'].apply(lambda x:x[x.find('h-')-3 :x.find('h-')].split('-')[1])
#meta['Series'] = meta['filename'].apply(lambda x:x[x.find('polyA_'):x.find('polyA_')+15].split('-')[0].split('_')[1])
#meta['SARS_CoV'] = meta['filename'].apply(lambda x:x[x.find('_S'):x.find('_S')+1].split('_')[0])
#meta['detachedcells'] = meta['filename'].apply(lambda x:x.find('detachedcells'))
meta['Phenotype'] = meta.Cell_Line +'_' +meta.Time_Point.astype('str')+'h'
meta['Mock'] = meta['filename'].apply(lambda x:x.find('mock'))
meta.loc[meta.Mock>-1,'Mock']= 1

In [20]:
meta

                          filename Cell_Line Time_Point  Phenotype  Mock
8      Calu3_polyA_series1-S2-4h-A     Calu3          4   Calu3_4h    -1
9      Calu3_polyA_series1-S2-4h-B     Calu3          4   Calu3_4h    -1
10    Calu3_polyA_series1-S2-12h-A     Calu3         12  Calu3_12h    -1
11    Calu3_polyA_series1-S2-12h-B     Calu3         12  Calu3_12h    -1
12    Calu3_polyA_series1-S2-24h-A     Calu3         24  Calu3_24h    -1
14    Calu3_polyA_series1-S2-24h-B     Calu3         24  Calu3_24h    -1
16   Calu3_polyA_series1-mock-4h-A     Calu3          4   Calu3_4h     1
17   Calu3_polyA_series1-mock-4h-B     Calu3          4   Calu3_4h     1
18  Calu3_polyA_series1-mock-24h-A     Calu3         24  Calu3_24h     1
19  Calu3_polyA_series1-mock-24h-B     Calu3         24  Calu3_24h     1
24     Calu3_polyA_series2-4h-S2-1     Calu3          4   Calu3_4h    -1
25     Calu3_polyA_series2-4h-S2-2     Calu3          4   Calu3_4h    -1
26   Calu3_polyA_series2-4h-mock-1     Calu3          4   Calu3_4h     1
27   Calu3_polyA_series2-4h-mock-2     Calu3          4   Calu3_4h     1
30     Calu3_polyA_series2-8h-S2-1     Calu3          8   Calu3_8h    -1
31     Calu3_polyA_series2-8h-S2-2     Calu3          8   Calu3_8h    -1
34    Calu3_polyA_series2-12h-S2-1     Calu3         12  Calu3_12h    -1
35    Calu3_polyA_series2-12h-S2-2     Calu3         12  Calu3_12h    -1
36  Calu3_polyA_series2-12h-mock-1     Calu3         12  Calu3_12h     1
37  Calu3_polyA_series2-12h-mock-2     Calu3         12  Calu3_12h     1
46             H1299_polyA_S2-4h-A     H1299          4   H1299_4h    -1
47             H1299_polyA_S2-4h-B     H1299          4   H1299_4h    -1
48            H1299_polyA_S2-12h-A     H1299         12  H1299_12h    -1
49            H1299_polyA_S2-12h-B     H1299         12  H1299_12h    -1
50            H1299_polyA_S2-24h-A     H1299         24  H1299_24h    -1
51            H1299_polyA_S2-24h-B     H1299         24  H1299_24h    -1
52            H1299_polyA_S2-36h-A     H1299         36  H1299_36h    -1
53            H1299_polyA_S2-36h-B     H1299         36  H1299_36h    -1
54           H1299_polyA_mock-4h-A     H1299          4   H1299_4h     1
55           H1299_polyA_mock-4h-B     H1299          4   H1299_4h     1
56          H1299_polyA_mock-36h-A     H1299         36  H1299_36h     1
57          H1299_polyA_mock-36h-B     H1299         36  H1299_36h     1

In [21]:
meta.loc[:,['Phenotype','Cell_Line','Time_Point']].drop_duplicates()

    Phenotype Cell_Line Time_Point
8    Calu3_4h     Calu3          4
10  Calu3_12h     Calu3         12
12  Calu3_24h     Calu3         24
30   Calu3_8h     Calu3          8
46   H1299_4h     H1299          4
48  H1299_12h     H1299         12
50  H1299_24h     H1299         24
52  H1299_36h     H1299         36

In [22]:
meta.loc[meta['Mock']==1,'Mock']  = 'Mock' 
meta.loc[meta['Mock']==-1,'Mock']  = 'Infected' 
meta.head()

                        filename Cell_Line Time_Point  Phenotype      Mock
8    Calu3_polyA_series1-S2-4h-A     Calu3          4   Calu3_4h  Infected
9    Calu3_polyA_series1-S2-4h-B     Calu3          4   Calu3_4h  Infected
10  Calu3_polyA_series1-S2-12h-A     Calu3         12  Calu3_12h  Infected
11  Calu3_polyA_series1-S2-12h-B     Calu3         12  Calu3_12h  Infected
12  Calu3_polyA_series1-S2-24h-A     Calu3         24  Calu3_24h  Infected

In [23]:
meta.Phenotype.value_counts()

Calu3_4h     8
Calu3_12h    6
Calu3_24h    4
H1299_4h     4
H1299_36h    4
Calu3_8h     2
H1299_24h    2
H1299_12h    2
Name: Phenotype, dtype: int64

In [24]:
meta.Mock.value_counts()

Infected    20
Mock        12
Name: Mock, dtype: int64

In [25]:
meta['Phenotype_Mock'] = meta['Phenotype']+'_'+meta['Mock'].astype('str')
meta['Phenotype_Mock'].value_counts()

Calu3_4h_Infected     4
Calu3_12h_Infected    4
Calu3_4h_Mock         4
Calu3_8h_Infected     2
Calu3_24h_Mock        2
Calu3_12h_Mock        2
H1299_24h_Infected    2
H1299_36h_Infected    2
H1299_4h_Mock         2
H1299_12h_Infected    2
H1299_36h_Mock        2
H1299_4h_Infected     2
Calu3_24h_Infected    2
Name: Phenotype_Mock, dtype: int64

In [26]:
meta.to_csv('data/time_series_study/metadata.csv')

In [27]:
import os
if not os.path.exists('data/time_series_study/FPKM_divided/'):
    os.makedirs('data/time_series_study/FPKM_divided/')
phenotypes = meta.Phenotype.unique().tolist()
for i in phenotypes:
    files = meta.loc[meta.Phenotype==i,'filename']
    healthy_files = [x for x in files if x.find('mock') =='Mock']
    infected_files = [x for x in files if x.find('mock') == 'Infected']
    df.loc[:,files].to_csv('data/time_series_study/FPKM_divided/'+i+'.csv')